### ISSUE TITLE
'maven-jar-plugin'-version not specified

### ISSUE THREAD

**Issue by AiyionPrime** [luhsra/MinimaxSimulator#48]
Currently the version of the `maven-jar-plugin` is not set properly, due to the fact that it's only defined in order to not use it at all.
As the project currently relies on maven 3.0.5 it's safe to require version `3.2.0` of the plugin, as it's supported.
This should be future-proof for another few years.

**Comment by prohde** [comment]
I integrated the change you proposed already in PR #41 along with the fix to the actual issue addressed since I noticed the warning during the build process.

**Comment by AiyionPrime** [comment]
In that case I won't open a PR for this.

**Comment by AiyionPrime** [comment]
#41 resolved this.
